/* tslint:disable */
/* eslint-disable */
/**
 * FP Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Medicament
 */
export interface Medicament {
    /**
     * 
     * @type {string}
     * @memberof Medicament
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Medicament
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof Medicament
     */
    photo?: string;
    /**
     * Medicaments that are available to order
     * @type {Array<string>}
     * @memberof Medicament
     */
    availableMedicaments?: Array<string>;
}

export function MedicamentFromJSON(json: any): Medicament {
    return MedicamentFromJSONTyped(json, false);
}

export function MedicamentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Medicament {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'age': !exists(json, 'age') ? undefined : json['age'],
        'photo': !exists(json, 'photo') ? undefined : json['photo'],
        'availableMedicaments': !exists(json, 'availableMedicaments') ? undefined : json['availableMedicaments'],
    };
}

export function MedicamentToJSON(value?: Medicament | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'age': value.age,
        'photo': value.photo,
        'availableMedicaments': value.availableMedicaments,
    };
}


