/* tslint:disable */
/* eslint-disable */
/**
 * FP Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    Medicament,
    MedicamentFromJSON,
    MedicamentToJSON,
} from '../models';

export interface ListOrdersRequest {
    nameId?: string;
    ageToApply?: string;
    page?: number;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * List of medicaments that use
     */
    async listOrdersRaw(requestParameters: ListOrdersRequest): Promise<runtime.ApiResponse<Array<Medicament>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.nameId !== undefined) {
            queryParameters['nameId'] = requestParameters.nameId;
        }

        if (requestParameters.ageToApply !== undefined) {
            queryParameters['ageToApply'] = requestParameters.ageToApply;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health/medOrders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedicamentFromJSON));
    }

    /**
     * List of medicaments that use
     */
    async listOrders(requestParameters: ListOrdersRequest): Promise<Array<Medicament>> {
        const response = await this.listOrdersRaw(requestParameters);
        return await response.value();
    }

}
